### PR TITLE
Specify custom buildpack derived from Heroku Ruby

### PR DESCRIPTION
**Pull request by Morendil**
This is intended to circumvent the need to commit Gemfile.lock with every GH-Pages version bump. We are pointing to our custom fork of the Heroku Ruby buildpack, which fools itself into always thinking its Gemfile.lock was generated on Windows, and therefore ignoring it.

### CODE REVIEW

**Comment by Morendil** [comment]
Verified to work as intended on https://betagouv-pr-392.herokuapp.com/ whose build log warns about discarding Gemfile.lock.

**Comment by MattiSG** [comment]
> SGMAP-bot had a problem deploying to betagouv-pr-392 8 minutes ago Failure

:wink:

>   Gemfile.lock required. Please check it in.

J'ai l'impression que le buildpack est aussi spécifié dans l'interface graphique, peut-être les deux entrent-ils en conflit… ?

**Comment by MattiSG** [comment]
(j'approuve mais il ne faut évidemment **pas merger** tant que le déploiement de la review app sur Heroku ne se passe pas correctement)

**Comment by Morendil** [comment]
Non, d'après mes tests préalables et la doc de Heroku c'est le app.json qui prend le pas sur ce qui est spécifié dans l'interface. Il est possible qu'il y ait des checks redondants sur la présence du Gemfile.lock, je vais investiguer.

**Comment by ys** [comment]
Two smells for me here:

- Not checking in the `Gemfile.lock` : http://bundler.io/v1.3/rationale.html#checking-your-code-into-version-control
- Using a custom buildpack.

I would rather add depencies explicitly into the `Gemfile` file. How often have you seen and got bitten by GitHub updating the dependencies?

Using a custom build pack... You will lack the updates, security patches and so on.
I would strongly advise you to understand what is happening here and use the default one over a fork.

**Comment by MattiSG** [comment]
Thanks for chiming in @ys!  :)

> How often have you seen and got bitten by GitHub updating the dependencies?

Lately, [almost once a day](https://github.com/sgmap/beta.gouv.fr/pulls?utf8=✓&q=is%3Apr%20pages). Getting annoying, and more importantly blocks contribution for people who contribute only through the GitHub UI.

> Using a custom build pack... You will lack the updates, security patches and so on.

Yes, we know 😞 That's why I asked if [we could have a flag](https://github.com/heroku/heroku-buildpack-ruby/issues/503), which was refused. The current implementation by @Morendil simply activates the default Windows behaviour from the standard build pack, so it both doesn't seem very dangerous and will be easy to merge from upstream.

> I would strongly advise you to understand what is happening here

Well, it seems to me we do understand: by using GitHub Pages as a production environment, we relinquish power over our production dependencies. This is the opposite of what is usually done when you deploy code, either on your own server or on some hosted platform like Heroku that would configure the environment for you.
So, what we do is we dynamically fetch the state of production on every install and ensure what we're developing on reflects production. Just like everyone does, except usually your code is dictating the production environment, whereas here we do the opposite :wink:

The current system where we check in the `Gemfile.lock` and have a dynamic `Gemfile` has the best of both worlds: we get a notification (locally and on CI) whenever the prod changes and we're forced to update, yet we can always go back in time.
However, the cost of maintaining this “time machine” behaviour is increasing, while its use-cases are, for the moment, inexistent (we only care about beta.gouv.fr being up and up to date). So this PR suggests losing that possibility, in exchange for more flexibility and avoiding contribution disruptions.

**Comment by MattiSG** [comment]
One more thing about forking the build pack: we only use Heroku for review apps, not for production, so even outdated security would not be a big risk.

**Comment by ys** [comment]
Thanks for this answer.

The buildpack, I would rather find and fix on my side than forking there. This seems easy now, but might not be in the future, when you will have to update the gem or anything else.

For the updates of prod gems, I would rather have a Gemfile generator in `bin/` that checks if it changed and apply changes but keep the `Gemfile` explicit and the `Gemfile.lock` everywhere.

This is a hassle you have to maintain, this is non standard Ruby you need to comment and explain to new people contributing, and so on. Many more downsides on the human side. This is not because Ruby let you do this that you should. This goes back to metaprogramming magic, abusing it will bite you later on the human side of the project.

But hey, again not my project:) Just happy to give my 2cts and congrats on using GitHub pages in prod with `.fr`

**Comment by MattiSG** [comment]
I must say I fail to see how exactly having a dynamic `bin` generator that generates a `Gemfile` (which then generates a `Gemfile.lock`) is any easier than having a dynamic `Gemfile` that generates a `Gemfile.lock` 🤔

As for the human side, as I mentioned above: the main contribution path is the web UI. The “no code” (not even a local clone) path outweighs the “Ruby contributors” path.

I think [this whole controversy](https://twitter.com/dmathieu/status/795584961633980416) comes from a basic misunderstanding: Ruby is only here as a side-effect of using Jekyll. This is not a Ruby project, this is just a GitHub Pages Jekyll instance 😉

Thanks for having taken the time to make your thoughts on that matter explicit! It surely helps us to articulate precisely the compromises we have to make 🙂

**Comment by Morendil** [comment]
En effet de nombreux éléments du buildpack Ruby s'appuient implicitement sur la présence d'un Gemfile.lock, notamment tous les appels à `has_gem` qui permettent de vérifier par exemple la présence d'execjs ou celle de la gem `pg` pour le add-on PostgreSQL... qui ne nous intéresse évidemment pas. J'ai réussi à passer outre tous ces checks (par exemple en prenant pour acquis que execjs est installé).

On va merger pour revenir à des conditions plus sereines d'utilisation des review apps, la discussion ci-dessus est à tout le moins un avertissement dont il faut tenir compte. En particulier, une partie du risque technique est désormais déportée sur https://github.com/sgmap/heroku-buildpack-ruby/

**Pull request merged**
