### PR TITLE
Add Alexia

### PR DESCRIPTION
**Pull request by maukoquiroga**
Closes #634

### CODE REVIEW

**Comment by maukoquiroga** [comment]
Done :)

**Comment by maukoquiroga** [comment]
The thing is @Morendil when one follow the instructions for adding oneself to the community via Github's GUI, you don't have push rights. That means you can't upload your image. Hence, CircleCI complains. Catch-22. Should we 1) Relax CI, 2) Update the Wiki or 3) I don't know ?

**Comment by Morendil** [comment]
@maukoquiroga Agreed, this pattern has caused frustration a few times now and improving that process is becoming an urgent need; I'd like to do some user testing IRL to understand where to focus effort.

**Comment by MattiSG** [comment]
I don't see exactly how that happens: if you use the click function, you're asked to fork the repo in order to modify it, and you can then upload a picture in your fork. Obviously, your first commit will make CI complain, but you can have a second one. What about just updating the instructions?

**Pull request merged**
