### PR TITLE
Check if startup links are valid

### PR DESCRIPTION
**Pull request by maukoquiroga**
Helps to keep portfolio updated and in sync with reality. See #671 . WDYT?

### CODE REVIEW

**Comment by Morendil** [comment]
My initial reaction is :-1: on the basis that checking external state is not the job of continuous integration tests. We do not want the build to break, blocking contributions, based on external events over which contributors have no control.

**Comment by maukoquiroga** [comment]
I agree with you in general terms: one should delegate performance and exploratory testing to non-blocking integration tasks. Although, there're some specificities here I'd like to invite you to consider.

What are we testing? We want to know if:

1. Our static site (not dynamically generated content)
2. within its  site/startup content (scope)
3. has a link (not an image or a script tag)
4. that is external
5. giving a 4xx status

That being said, I can only imagine a handful of cases where 1-5 holds true:

1. Layer 8 (someone mistyped or forgot to update a link)
2. A startup died (it would be blocking had startups die more often, which then would be a rather happy problem)
3. Finally Google has replaced nation-states and a singularity robot made an internet coup d'état to replace 4xx status with 5xx

Based on the practicality of the former and the unlikeliness for the latter, specially 3., I think it is a good compromise.

**Comment by Morendil** [comment]
Still unconvinced. In the general case, I doubt that this check will ever trigger, and if it does the only outcomes I anticipate are confusion and frustration. In the specific case, it's not clear that this check would have triggered for retraite.beta.gouv.fr (a CNAME pointing to a server taken down, not a 404), nor does this PR improve the situation with retraite in any way.

Checking liveness is a job for UptimeRobot, or https://verif.site. I'm going to be an abstentionist as far as reviewing this PR is concerned. ;)

**Comment by maukoquiroga** [comment]
Mmm... so after giving this a thought, I think it would be a better idea to delegate the up-to-dateness of links check to an external service. Still, the job-to-be-done remains to have an actionable feedback to help keep the « fiche produit » up to date, and no longer sure how it could deliver on that premise. Closing for now.

**Pull request closed without merging**
