### PR TITLE
Optimize authors and startups images

### PR DESCRIPTION
**Pull request by davidbgk**
capture d ecran 2017-02-21 a 13 59 21
capture d ecran 2017-02-21 a 14 01 26

Current status:

* https://www.webpagetest.org/result/170221_Y0_14M4/
* https://www.webpagetest.org/result/170221_HY_14NX/
* https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fbeta.gouv.fr%2Fstartups.html&tab=desktop
* https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fbeta.gouv.fr%2Fcommunaute.html&tab=desktop

Images should be resized too, especially authors.

### CODE REVIEW

**Comment by MattiSG** [comment]
I do it on on PRs I merge manually, this should be enforced upon accepting a PR.

**Comment by MattiSG** [comment]
@davidbgk I'm surprised you could save a few kB on so many PNGs that I'm pretty sure I optimised manually beforehand. Did you remove “additional chunks” in ImageOptim?

**Comment by davidbgk** [comment]
@MattiSG yes I turned on that option.

By the way, I saw there is an [ongoing PR](https://github.com/sgmap/beta.gouv.fr/pull/503) to fix the size of one image, I think it should be generalized. I didn't optimized images contained within the `posts` folder because of this but there is room for improvements there too.

**Comment by MattiSG** [comment]
Superseded by #523.

**Pull request closed without merging**
